### ISSUE TITLE
too ez

### ISSUE THREAD

**Issue by co3moz** [erayarslan/CatchMeIfYouCan#1]
Please add levels "dumblike", "casual", "prolike", "godlike".

**Comment by erayarslan** [comment]
Bu test için bi proje sonrasına üşenmezsem amacı farklı zaten :smile: 
Forkla kendin ayrı proje olarak devam et ekle :facepunch:

**Comment by co3moz** [comment]
Kanki yapak bir tane mmorpg.js :smile:

**Comment by erayarslan** [comment]
yaptık biz :D

**Comment by co3moz** [comment]
Hadi ya nası bişi oldu :smiley:
